# src/player_map.py
"""
Mapping of superstar player names to their current teams.
Used for resolving 'Game not found' errors in prop bets where the team isn't mentioned.
"""

PLAYER_TO_TEAM_MAP = {
    # NBA
    "lebron": "Los Angeles Lakers",
    "lebron james": "Los Angeles Lakers",
    "ad": "Los Angeles Lakers",
    "anthony davis": "Los Angeles Lakers",
    "curry": "Golden State Warriors",
    "steph curry": "Golden State Warriors",
    "stephen curry": "Golden State Warriors",
    "luka": "Dallas Mavericks",
    "luka doncic": "Dallas Mavericks",
    "doncic": "Dallas Mavericks",
    "kyrie": "Dallas Mavericks",
    "kyrie irving": "Dallas Mavericks",
    "giannis": "Milwaukee Bucks",
    "antetokounmpo": "Milwaukee Bucks",
    "dame": "Milwaukee Bucks",
    "damian lillard": "Milwaukee Bucks",
    "embiid": "Philadelphia 76ers",
    "embid": "Philadelphia 76ers",
    "joel embiid": "Philadelphia 76ers",
    "maxey": "Philadelphia 76ers",
    "tyrese maxey": "Philadelphia 76ers",
    "tatum": "Boston Celtics",
    "jayson tatum": "Boston Celtics",
    "brown": "Boston Celtics", # Risk of ambiguity, but Jaylen is most common star
    "jaylen brown": "Boston Celtics",
    "jokic": "Denver Nuggets",
    "nikola jokic": "Denver Nuggets",
    "murray": "Denver Nuggets", # Jamal
    "jamal murray": "Denver Nuggets",
    "shai": "Oklahoma City Thunder",
    "sga": "Oklahoma City Thunder",
    "gilgeous-alexander": "Oklahoma City Thunder",
    "chet": "Oklahoma City Thunder",
    "holmgren": "Oklahoma City Thunder",
    "edwards": "Minnesota Timberwolves",
    "anthony edwards": "Minnesota Timberwolves",
    "ant": "Minnesota Timberwolves", # Nickname
    "kat": "Minnesota Timberwolves", # Karl-Anthony Towns (Wait, traded to Knicks!)
    "randle": "Minnesota Timberwolves",
    "julius randle": "Minnesota Timberwolves",
    "brunson": "New York Knicks",
    "jalen brunson": "New York Knicks",
    "towns": "New York Knicks",
    "karl-anthony towns": "New York Knicks",
    "hart": "New York Knicks",
    "josh hart": "New York Knicks",
    "wemby": "San Antonio Spurs",
    "wembanyama": "San Antonio Spurs",
    "victor wembanyama": "San Antonio Spurs",
    "booker": "Phoenix Suns",
    "devin booker": "Phoenix Suns",
    "kd": "Phoenix Suns",
    "durant": "Phoenix Suns",
    "kevin durant": "Phoenix Suns",
    "beal": "Phoenix Suns",
    "fox": "Sacramento Kings",
    "deaaron fox": "Sacramento Kings",
    "sabonis": "Sacramento Kings",
    "domantas sabonis": "Sacramento Kings",
    "haliburton": "Indiana Pacers",
    "tyrese haliburton": "Indiana Pacers",
    "siakam": "Indiana Pacers",
    "pascal siakam": "Indiana Pacers",
    "butler": "Miami Heat",
    "jimmy butler": "Miami Heat",
    "bam": "Miami Heat",
    "adebayo": "Miami Heat",
    "bam adebayo": "Miami Heat",
    "herro": "Miami Heat",
    "tyler herro": "Miami Heat",
    "trae": "Atlanta Hawks",
    "trae young": "Atlanta Hawks",
    "lamelo": "Charlotte Hornets",
    "lamelo ball": "Charlotte Hornets",
    "miller": "Charlotte Hornets", # Brandon Miller
    "cunningham": "Detroit Pistons",
    "cade cunningham": "Detroit Pistons",
    "paolo": "Orlando Magic",
    "banchero": "Orlando Magic",
    "franz": "Orlando Magic",
    "franz wagner": "Orlando Magic",
    "mitchell": "Cleveland Cavaliers",
    "donovan mitchell": "Cleveland Cavaliers",
    "garland": "Cleveland Cavaliers",
    "darius garland": "Cleveland Cavaliers",
    "mobley": "Cleveland Cavaliers",
    "evan mobley": "Cleveland Cavaliers",
    "allen": "Cleveland Cavaliers", # Jarrett Allen
    "jarrett allen": "Cleveland Cavaliers",
    "zion": "New Orleans Pelicans",
    "williamson": "New Orleans Pelicans",
    "ingram": "New Orleans Pelicans",
    "bi": "New Orleans Pelicans", # Brandon Ingram
    "ja": "Memphis Grizzlies",
    "morant": "Memphis Grizzlies",
    "ja morant": "Memphis Grizzlies",
    "jjj": "Memphis Grizzlies",
    "jaren jackson": "Memphis Grizzlies",
    "bane": "Memphis Grizzlies",
    "desmond bane": "Memphis Grizzlies",
    "lauri": "Utah Jazz",
    "markkanen": "Utah Jazz",
    "sexton": "Utah Jazz",
    "collin sexton": "Utah Jazz",
    "sengun": "Houston Rockets",
    "alperen sengun": "Houston Rockets",
    "vanvleet": "Houston Rockets",
    "fred vanvleet": "Houston Rockets",
    "green": "Houston Rockets", # Jalen Green (Ambiguous with Draymond/Jeff/etc but Jalen is primary scorer)
    "jalen green": "Houston Rockets",
    "harden": "Los Angeles Clippers",
    "james harden": "Los Angeles Clippers",
    "kawhi": "Los Angeles Clippers",
    "leanord": "Los Angeles Clippers", # Typo catch
    "leonard": "Los Angeles Clippers",
    "kawhi leonard": "Los Angeles Clippers",
    "pg": "Philadelphia 76ers", # Paul George (Traded to 76ers)
    "paul george": "Philadelphia 76ers",
    "klay": "Dallas Mavericks", # Traded to Dallas
    "klay thompson": "Dallas Mavericks",
    "cp3": "San Antonio Spurs", # Traded to Spurs
    "chris paul": "San Antonio Spurs",
    "demar": "Sacramento Kings", # Traded to Kings
    "derozan": "Sacramento Kings",
    "demar derozan": "Sacramento Kings",
    "bridges": "New York Knicks", # Mikal Bridges
    "mikal bridges": "New York Knicks",
}
