# src/team_aliases.py

TEAM_ALIASES = {
  "yankees": ["yankees", "new york yankees"],
  "red sox": ["red sox", "boston red sox"],
  "blue jays": ["blue jays", "toronto blue jays"],
  "orioles": ["orioles", "baltimore orioles"],
  "rays": ["rays", "tampa bay rays"],
  "white sox": ["white sox", "chicago white sox"],
  "guardians": ["guardians", "cleveland guardians"],
  "tigers": ["tigers", "detroit tigers"],
  "royals": ["royals", "kansas city royals"],
  "twins": ["twins", "minnesota twins"],
  "astros": ["astros", "houston astros"],
  "mariners": ["mariners", "seattle mariners"],
  "rangers": ["rangers", "texas rangers"],
  "angels": ["angels", "los angeles angels"],
  "athletics": ["athletics", "oakland athletics", "a's", "oakland a's"],
  "braves": ["braves", "atlanta braves"],
  "marlins": ["marlins", "miami marlins"],
  "mets": ["mets", "new york mets"],
  "phillies": ["phillies", "philadelphia phillies"],
  "nationals": ["nationals", "washington nationals"],
  "cubs": ["cubs", "chicago cubs"],
  "reds": ["reds", "cincinnati reds"],
  "brewers": ["brewers", "milwaukee brewers"],
  "pirates": ["pirates", "pittsburgh pirates"],
  "cardinals": ["cardinals", "st. louis cardinals"],
  "dodgers": ["dodgers", "los angeles dodgers"],
  "giants": ["giants", "san francisco giants"],
  "padres": ["padres", "san diego padres"],
  "rockies": ["rockies", "colorado rockies"],
  "diamondbacks": ["diamondbacks", "arizona diamondbacks", "dbacks", "arizona dbacks"],
  "hawks": ["hawks", "atlanta hawks"],
  "celtics": ["celtics", "boston celtics"],
  "nets": ["nets", "brooklyn nets"],
  "hornets": ["hornets", "charlotte hornets"],
  "bulls": ["bulls", "chicago bulls"],
  "cavaliers": ["cavaliers", "cleveland cavaliers", "cavs", "cleveland cavs"],
  "mavericks": ["mavericks", "dallas mavericks"],
  "nuggets": ["nuggets", "denver nuggets"],
  "pistons": ["pistons", "detroit pistons"],
  "warriors": ["warriors", "golden state warriors"],
  "rockets": ["rockets", "houston rockets"],
  "pacers": ["pacers", "indiana pacers"],
  "clippers": ["clippers", "los angeles clippers"],
  "lakers": ["lakers", "los angeles lakers"],
  "grizzlies": ["grizzlies", "memphis grizzlies"],
  "heat": ["heat", "miami heat"],
  "bucks": ["bucks", "milwaukee bucks"],
  "timberwolves": ["timberwolves", "minnesota timberwolves"],
  "pelicans": ["pelicans", "new orleans pelicans"],
  "knicks": ["knicks", "new york knicks"],
  "thunder": ["thunder", "oklahoma city thunder"],
  "magic": ["magic", "orlando magic"],
  "76ers": ["sixers", "philadelphia 76ers", "76ers", "philadelphia sixers"],
  "suns": ["suns", "phoenix suns"],
  "blazers": ["blazers", "portland blazers", "trailblazers", "portland trailblazers"],
  "kings": ["kings", "sacramento kings"],
  "spurs": ["spurs", "san antonio spurs"],
  "raptors": ["raptors", "toronto raptors"],
  "jazz": ["jazz", "utah jazz"],
  "wizards": ["wizards", "washington wizards"],
  "falcons": ["falcons", "atlanta falcons"],
  "ravens": ["ravens", "baltimore ravens"],
  "bills": ["bills", "buffalo bills"],
  "panthers": ["panthers", "carolina panthers"],
  "bears": ["bears", "chicago bears"],
  "bengals": ["bengals", "cincinnati bengals"],
  "browns": ["browns", "cleveland browns"],
  "cowboys": ["cowboys", "dallas cowboys"],
  "broncos": ["broncos", "denver broncos"],
  "lions": ["lions", "detroit lions"],
  "packers": ["packers", "green bay packers"],
  "texans": ["texans", "houston texans"],
  "colts": ["colts", "indianapolis colts"],
  "jaguars": ["jaguars", "jacksonville jaguars", "jags"],
  "chiefs": ["chiefs", "kansas city chiefs"],
  "raiders": ["raiders", "las vegas raiders"],
  "chargers": ["chargers", "los angeles chargers"],
  "rams": ["rams", "los angeles rams"],
  "dolphins": ["dolphins", "miami dolphins"],
  "vikings": ["vikings", "minnesota vikings"],
  "patriots": ["patriots", "new england patriots"],
  "saints": ["saints", "new orleans saints"],
  "jets": ["jets", "new york jets"],
  "eagles": ["eagles", "philadelphia eagles"],
  "steelers": ["steelers", "pittsburgh steelers"],
  "49ers": ["49ers", "san francisco 49ers"],
  "seahawks": ["seahawks", "seattle seahawks"],
  "buccaneers": ["buccaneers", "tampa bay buccaneers", "bucs"],
  "titans": ["titans", "tennessee titans"],
  "commanders": ["commanders", "washington commanders"],
  "ducks": ["ducks", "anaheim ducks"],
  "coyotes": ["coyotes", "arizona coyotes"],
  "bruins": ["bruins", "boston bruins"],
  "sabres": ["sabres", "buffalo sabres"],
  "flames": ["flames", "calgary flames"],
  "hurricanes": ["hurricanes", "carolina hurricanes"],
  "blackhawks": ["blackhawks", "chicago blackhawks"],
  "avalanche": ["avalanche", "colorado avalanche"],
  "blue jackets": ["blue jackets", "columbus blue jackets"],
  "stars": ["stars", "dallas stars"],
  "red wings": ["red wings", "detroit red wings"],
  "oilers": ["oilers", "edmonton oilers"],
  "wild": ["wild", "minnesota wild"],
  "canadiens": ["canadiens", "montreal canadiens"],
  "predators": ["predators", "nashville predators"],
  "devils": ["devils", "new jersey devils"],
  "islanders": ["islanders", "new york islanders"],
  "rangers": ["rangers", "new york rangers"],
  "senators": ["senators", "ottawa senators"],
  "flyers": ["flyers", "philadelphia flyers"],
  "mammoth": ["mammoth", "utah mammoth"],
  "penguins": ["penguins", "pittsburgh penguins"],
  "sharks": ["sharks", "san jose sharks"],
  "kraken": ["kraken", "seattle kraken"],
  "blues": ["blues", "st. louis blues"],
  "lightning": ["lightning", "tampa bay lightning"],
  "maple leafs": ["maple leafs", "toronto maple leafs", "leafs"],
  "canucks": ["canucks", "vancouver canucks"],
  "golden knights": ["golden knights", "vegas golden knights"],
  "capitals": ["capitals", "washington capitals"],
  "jets": ["jets", "winnipeg jets"],
  "dream": ["dream", "atlanta dream"],
  "sky": ["sky", "chicago sky"],
  "sun": ["sun", "connecticut sun"],
  "wings": ["wings", "dallas wings"],
  "fever": ["fever", "indiana fever"],
  "aces": ["aces", "las vegas aces"],
  "sparks": ["sparks", "los angeles sparks"],
  "lynx": ["lynx", "minnesota lynx"],
  "liberty": ["liberty", "new york liberty"],
  "mercury": ["mercury", "phoenix mercury"],
  "storm": ["storm", "seattle storm"],
  "mystics": ["mystics", "washington mystics"],
  "valkyries": ["valkyries", "golden state valkyries"],
  "abilene christian wildcats": ["abilene christian", "abilene christian wildcats", "acu"],
  "air force falcons": ["af", "air force", "air force falcons"],
  "akron zips": ["akron", "akron zips"],
  "alabama a&m bulldogs": ["aam", "alabama a&m", "alabama a&m bulldogs"],
  "alabama crimson tide": ["ala", "alabama", "alabama crimson tide", "bama", "crimson tide"],
  "alabama state hornets": ["alab st", "alabama st hornets", "alabama state", "alabama state hornets"],
  "albany great danes": ["alb", "albany", "albany great danes", "great danes"],
  "alcorn state braves": ["alc", "alcorn st braves", "alcorn state", "alcorn state braves"],
  "american eagles": ["american", "american university", "amercan"],
  "appalachian state mountaineers": ["app", "appalachian st mountaineers", "appalachian state", "appalachian state mountaineers"],
  "arizona state sun devils": ["arizona st sun devils", "arizona state", "arizona state sun devils", "asu", "sun devils"],
  "arizona wildcats": ["ariz", "arizona", "arizona wildcats"],
  "arkansas razorbacks": ["ark", "arkansas", "arkansas razorbacks", "razorbacks"],
  "arkansas state red wolves": ["ark st", "ark st red wolves", "arkansas state", "arkansas state red wolves", "red wolves"],
  "arkansas-pine bluff golden lions": ["arkansas-pine bluff", "arkansas-pine bluff golden lions", "golden lions", "uapb"],
  "army black knights": ["army", "army black knights", "black knights"],
  "auburn tigers": ["aub", "auburn", "auburn tigers"],
  "austin peay governors": ["apsu", "austin peay", "austin peay governors"],
  "ball state cardinals": ["ball st", "ball st cardinals", "ball state", "ball state cardinals"],
  "baylor bears": ["bay", "baylor", "baylor bears"],
  "bellarmine knights": ["bell", "bellarmine", "bellarmine knights"],
  "belmont bruins": ["bel", "belmont", "belmont bruins"],
  "bethune-cookman wildcats": ["b-cu", "bethune-cookman", "bethune-cookman wildcats"],
  "binghamton bearcats": ["bing", "binghamton", "binghamton bearcats"],
  "boise state broncos": ["boise st", "boise st broncos", "boise state", "boise state broncos"],
  "boston college eagles": ["bc", "boston college", "boston college eagles"],
  "boston university terriers": ["boston u", "boston university", "boston university terriers"],
  "bowling green falcons": ["bgsu", "bowling green", "bowling green falcons"],
  "bradley braves": ["brad", "bradley", "bradley braves"],
  "brown bears": ["brwn", "brown", "brown bears"],
  "bryant bulldogs": ["bry", "bryant", "bryant bulldogs"],
  "bucknell bison": ["buck", "bucknell", "bucknell bison"],
  "buffalo bulls": ["buf", "buffalo", "buffalo bulls"],
  "butler bulldogs": ["but", "butler", "butler bulldogs"],
  "byu cougars": ["byu", "byu cougars"],
  "cal baptist lancers": ["cal baptist", "cal baptist lancers", "cbu"],
  "cal poly mustangs": ["cal poly", "cal poly mustangs", "cp"],
  "california golden bears": ["cal", "california", "california golden bears", "golden bears"],
  "campbell fighting camels": ["camp", "campbell", "campbell fighting camels", "fighting camels"],
  "canisius golden griffins": ["can", "canisius", "canisius golden griffins", "golden griffins"],
  "central arkansas bears": ["central arkansas", "central arkansas bears", "uca"],
  "central connecticut blue devils": ["ccsu", "central connecticut", "central connecticut blue devils", "blue devils"],
  "central michigan chippewas": ["central michigan", "central michigan chippewas", "chippewas", "cmu"],
  "charleston cougars": ["charleston", "charleston cougars", "cofc"],
  "charleston southern buccaneers": ["charleston southern", "charleston southern buccaneers", "csu"],
  "charlotte 49ers": ["49ers", "charlotte", "charlotte 49ers", "clt"],
  "chattanooga mocs": ["chatt", "chattanooga", "chattanooga mocs"],
  "chicago state cougars": ["chicago st cougars", "chicago state", "chicago state cougars", "csu"],
  "cincinnati bearcats": ["cin", "cincinnati", "cincinnati bearcats"],
  "clemson tigers": ["clem", "clemson", "clemson tigers"],
  "cleveland state vikings": ["cleveland st vikings", "cleveland state", "cleveland state vikings", "csu"],
  "coastal carolina chanticleers": ["ccu", "chanticleers", "coastal carolina", "coastal carolina chanticleers"],
  "colgate raiders": ["colg", "colgate", "colgate raiders"],
  "college of charleston cougars": ["college of charleston", "college of charleston cougars"],
  "colorado buffaloes": ["col", "colorado", "colorado buffaloes"],
  "colorado state rams": ["colorado st rams", "colorado state", "colorado state rams", "csu"],
  "columbia lions": ["clmb", "columbia", "columbia lions"],
  "coppin state eagles": ["coppin st eagles", "coppin state", "coppin state eagles", "copp"],
  "cornell big red": ["big red", "cornell", "cornell big red", "crnl"],
  "creighton bluejays": ["crei", "creighton", "creighton bluejays"],
  "csun matadors": ["csun", "csun matadors"],
  "dartmouth big green": ["big green", "dart", "dartmouth", "dartmouth big green"],
  "davidson wildcats": ["davidson", "davidson wildcats", "dav"],
  "dayton flyers": ["day", "dayton", "dayton flyers"],
  "delaware blue hens": ["blue hens", "del", "delaware", "delaware blue hens"],
  "delaware state hornets": ["del st", "del st hornets", "delaware state", "delaware state hornets"],
  "denver pioneers": ["denv", "denver", "denver pioneers"],
  "depaul blue demons": ["blue demons", "dep", "depaul", "depaul blue demons"],
  "detroit mercy titans": ["detroit mercy", "detroit mercy titans", "det"],
  "drake bulldogs": ["drake", "drake bulldogs", "drke"],
  "drexel dragons": ["drex", "drexel", "drexel dragons"],
  "duke blue devils": ["blue devils", "duke", "duke blue devils"],
  "duquesne dukes": ["duq", "duquesne", "duquesne dukes"],
  "east carolina pirates": ["east carolina", "east carolina pirates", "ecu"],
  "east tennessee state buccaneers": ["east tenn st buccaneers", "east tennessee state", "east tennessee state buccaneers", "etsu"],
  "eastern illinois panthers": ["eastern illinois", "eastern illinois panthers", "eiu"],
  "eastern kentucky colonels": ["eastern kentucky", "eastern kentucky colonels", "eku"],
  "eastern michigan eagles": ["eastern michigan", "eastern michigan eagles", "emu"],
  "eastern washington eagles": ["eastern washington", "eastern washington eagles", "ewu"],
  "elon phoenix": ["elon", "elon phoenix"],
  "evansville purple aces": ["evansville", "evansville purple aces", "evan", "purple aces"],
  "fairfield stags": ["fair", "fairfield", "fairfield stags"],
  "fairleigh dickinson knights": ["fairleigh dickinson", "fairleigh dickinson knights", "fdu"],
  "florida international panthers": ["fiu", "florida international", "fiu panthers"],
  "florida a&m rattlers": ["famu", "florida a&m", "florida a&m rattlers"],
  "florida atlantic owls": ["fau", "florida atlantic", "florida atlantic owls"],
  "florida gators": ["fla", "florida", "florida gators", "uf"],
  "florida gulf coast eagles": ["fgcu", "florida gulf coast", "florida gulf coast eagles"],
  "florida state seminoles": ["florida st seminoles", "florida state", "florida state seminoles", "fsu", "seminoles"],
  "fordham rams": ["ford", "fordham", "fordham rams"],
  "fresno state bulldogs": ["fresno st bulldogs", "fresno state", "fresno state bulldogs", "fresno"],
  "furman paladins": ["fur", "furman", "furman paladins"],
  "gardner-webb runnin' bulldogs": ["gardner-webb", "gardner-webb runnin' bulldogs", "g-w", "runnin' bulldogs"],
  "george mason patriots": ["george mason", "george mason patriots", "gmu"],
  "george washington colonials": ["colonials", "george washington", "george washington colonials", "gw"],
  "georgetown hoyas": ["georgetown", "georgetown hoyas", "hoyas"],
  "georgia bulldogs": ["ga", "georgia", "georgia bulldogs"],
  "georgia southern eagles": ["georgia southern", "georgia southern eagles", "gaso"],
  "georgia state panthers": ["ga st", "ga st panthers", "georgia state", "georgia state panthers"],
  "georgia tech yellow jackets": ["ga tech", "georgia tech", "georgia tech yellow jackets", "gt", "yellow jackets"],
  "gonzaga bulldogs": ["gonz", "gonzaga", "gonzaga bulldogs"],
  "grambling tigers": ["gram", "grambling", "grambling tigers"],
  "grand canyon antelopes": ["gcu", "grand canyon", "grand canyon antelopes"],
  "green bay phoenix": ["gb", "green bay", "green bay phoenix"],
  "hampton pirates": ["hamp", "hampton", "hampton pirates"],
  "hartford hawks": ["hart", "hartford", "hartford hawks"],
  "harvard crimson": ["crimson", "harv", "harvard", "harvard crimson"],
  "hawaii rainbow warriors": ["hawaii", "hawaii rainbow warriors", "hawai'i", "hawai'i rainbow warriors", "haw", "rainbow warriors"],
  "high point panthers": ["high point", "high point panthers", "hpu"],
  "hofstra pride": ["hof", "hofstra", "hofstra pride"],
  "holy cross crusaders": ["crusaders", "hc", "holy cross", "holy cross crusaders"],
  "houston baptist huskies": ["houston baptist", "houston baptist huskies", "hbu"],
  "houston cougars": ["hou", "houston", "houston cougars"],
  "howard bison": ["how", "howard", "howard bison"],
  "idaho state bengals": ["idaho st bengals", "idaho state", "idaho state bengals", "idst"],
  "idaho vandals": ["idaho", "idaho vandals", "idah"],
  "illinois fighting illini": ["fighting illini", "ill", "illini", "illinois", "illinois fighting illini"],
  "illinois state redbirds": ["illinois st redbirds", "illinois state", "illinois state redbirds", "ilst"],
  "incarnate word cardinals": ["incarnate word", "incarnate word cardinals", "uiw"],
  "indiana hoosiers": ["hoosiers", "ind", "indiana", "indiana hoosiers"],
  "indiana state sycamores": ["indiana st sycamores", "indiana state", "indiana state sycamores", "ins"],
  "iona gaels": ["iona", "iona gaels"],
  "iowa hawkeyes": ["hawkeyes", "iowa", "iowa hawkeyes"],
  "iowa state cyclones": ["cyclones", "iowa st cyclones", "iowa state", "iowa state cyclones", "isu", "iowa st"],
  "iupui jaguars": ["iupui", "iupui jaguars"],
  "jackson state tigers": ["jackson st tigers", "jackson state", "jackson state tigers", "jkst"],
  "jacksonville dolphins": ["jacksonville", "jacksonville dolphins", "jax"],
  "jacksonville state gamecocks": ["gamecocks", "jacksonville st gamecocks", "jacksonville state", "jacksonville state gamecocks", "jax st"],
  "james madison dukes": ["james madison", "james madison dukes", "jmu"],
  "kansas jayhawks": ["jayhawks", "kan", "kansas", "kansas jayhawks"],
  "kansas state wildcats": ["k-state", "kansas st", "k state", "kansas st wildcats", "kansas state", "kansas state wildcats", "ks"],
  "kennesaw state owls": ["kennesaw st owls", "kennesaw state", "kennesaw state owls", "kns"],
  "kent state golden flashes": ["golden flashes", "kent", "kent st golden flashes", "kent state", "kent state golden flashes"],
  "kentucky wildcats": ["kentucky", "kentucky wildcats", "uk"],
  "la salle explorers": ["la salle", "la salle explorers", "las"],
  "lafayette leopards": ["laf", "lafayette", "lafayette leopards"],
  "lamar cardinals": ["lam", "lamar", "lamar cardinals"],
  "lehigh mountain hawks": ["leh", "lehigh", "lehigh mountain hawks", "mountain hawks"],
  "liberty flames": ["lib", "flames", "liberty", "liberty flames"],
  "lindenwood lions": ["lindenwood", "lindenwood lions"],
  "lipscomb bisons": ["lip", "lipscomb", "lipscomb bisons"],
  "little rock trojans": ["little rock", "little rock trojans", "lr"],
  "long beach state beach": ["beach", "long beach st beach", "long beach state", "long beach state beach", "lbsu"],
  "long island sharks": ["liu", "long island", "long island sharks"],
  "longwood lancers": ["lng", "longwood", "longwood lancers"],
  "louisiana raging cajuns": ["louisiana", "louisiana raging cajuns", "raging cajuns", "ull"],
  "louisiana tech bulldogs": ["la tech", "latech", "louisiana tech", "louisiana tech bulldogs"],
  "louisville cardinals": ["lou", "louisville", "louisville cardinals"],
  "loyola chicago ramblers": ["loyola chicago", "loyola-chicago", "loyola chicago ramblers", "loyc"],
  "loyola marymount lions": ["lmu", "loyola marymount", "loyola marymount lions"],
  "loyola (md) greyhounds": ["loyola (md)", "loyola (md) greyhounds", "loymd"],
  "lsu tigers": ["louisiana state", "louisiana st", "lsu", "lsu tigers"],
  "maine black bears": ["black bears", "maine", "maine black bears", "me"],
  "manhattan jaspers": ["man", "manhattan", "manhattan jaspers"],
  "marist red foxes": ["marist", "marist red foxes", "mrs", "red foxes"],
  "marquette golden eagles": ["marquette", "marquette golden eagles", "marq"],
  "marshall thundering herd": ["marshall", "marshall thundering herd", "marsh", "thundering herd"],
  "maryland eastern shore hawks": ["maryland eastern shore", "maryland eastern shore hawks", "umes"],
  "maryland terrapins": ["maryland", "maryland terrapins", "md", "terrapins"],
  "mcneese cowboys": ["mcneese", "mcneese cowboys", "mcns"],
  "memphis tigers": ["memphis", "memphis tigers", "mem"],
  "mercer bears": ["mer", "mercer", "mercer bears"],
  "merrimack warriors": ["merrimack", "merrimack warriors", "merr"],
  "miami hurricanes": ["canes", "hurricanes", "miami", "miami (fl)", "miami hurricanes"],
  "miami (oh) redhawks": ["miami (oh)", "miami (oh) redhawks", "mioh", "redhawks"],
  "michigan state spartans": ["michigan st spartans", "michigan state", "michigan state spartans", "msu"],
  "michigan wolverines": ["mich", "michigan", "michigan wolverines", "wolverines"],
  "middle tennessee blue raiders": ["blue raiders", "middle tenn st blue raiders", "middle tennessee", "middle tennessee blue raiders", "mtsu"],
  "milwaukee panthers": ["milwaukee", "milwaukee panthers", "milw"],
  "minnesota golden gophers": ["golden gophers", "minn", "minnesota", "minnesota golden gophers"],
  "mississippi state bulldogs": ["mississippi st bulldogs", "miss state", "mississippi state", "mississippi state bulldogs", "msst"],
  "mississippi valley state delta devils": ["delta devils", "mississippi valley st delta devils", "mississippi valley state", "mississippi valley state delta devils", "mvsu"],
  "missouri state bears": ["missouri st bears", "missouri state", "missouri state bears", "mos"],
  "missouri tigers": ["missouri", "missouri tigers", "mizz", "mizzou"],
  "monmouth hawks": ["monm", "monmouth", "monmouth hawks"],
  "montana grizzlies": ["montana", "montana grizzlies", "mont"],
  "montana state bobcats": ["montana st bobcats", "montana state", "montana state bobcats", "mts"],
  "morehead state eagles": ["morehead st eagles", "morehead state", "morehead state eagles", "mrhe"],
  "morgan state bears": ["morgan st bears", "morgan state", "morgan state bears", "morg"],
  "mount st. mary's mountaineers": ["mount st. mary's", "mount st. mary's mountaineers", "msm"],
  "murray state racers": ["murray st racers", "murray state", "murray state racers", "murs"],
  "navy midshipmen": ["midshipmen", "navy", "navy midshipmen"],
  "nc state wolfpack": ["nc st wolfpack", "N.C. State", "nc state", "nc state wolfpack", "north carolina state", "north carolina st", "wolfpack"],
  "nebraska cornhuskers": ["cornhuskers", "neb", "nebraska", "nebraska cornhuskers"],
  "nevada wolf pack": ["nevada", "nevada wolf pack", "unlv", "wolf pack"],
  "new hampshire wildcats": ["new hampshire", "new hampshire wildcats", "unh"],
  "new mexico lobos": ["lobos", "new mexico", "new mexico lobos", "nm"],
  "new mexico state aggies": ["new mexico st aggies", "new mexico state", "new mexico state aggies", "nmsu"],
  "new orleans privateers": ["new orleans", "new orleans privateers", "uno"],
  "niagara purple eagles": ["niagara", "niagara purple eagles", "purple eagles"],
  "nicholls colonels": ["nicholls", "nicholls colonels", "nich"],
  "njit highlanders": ["njit", "njit highlanders"],
  "norfolk state spartans": ["norfolk st spartans", "norfolk state", "norfolk state spartans", "norf"],
  "north alabama lions": ["north alabama", "north alabama lions", "una"],
  "north carolina a&t aggies": ["north carolina a&t", "north carolina a&t aggies", "ncat"],
  "north carolina central eagles": ["nc central", "north carolina central", "north carolina central eagles"],
  "north carolina tar heels": ["north carolina", "north carolina tar heels", "tar heels", "unc"],
  "north dakota fighting hawks": ["fighting hawks", "north dakota", "north dakota fighting hawks", "und"],
  "north dakota state bison": ["ndsu", "north dakota st bison", "north dakota state", "north dakota state bison"],
  "north florida ospeys": ["north florida", "north florida ospeys", "unf"],
  "north texas mean green": ["mean green", "north texas", "north texas mean green", "unt"],
  "northeastern huskies": ["northeastern", "northeastern huskies", "ne"],
  "northern arizona lumberjacks": ["lumberjacks", "nau", "northern arizona", "northern arizona lumberjacks"],
  "northern colorado bears": ["northern colorado", "northern colorado bears", "unco"],
  "northern illinois huskies": ["niu", "northern illinois", "northern illinois huskies"],
  "northern iowa panthers": ["northern iowa", "northern iowa panthers", "uni"],
  "northern kentucky norse": ["nku", "northern kentucky", "northern kentucky norse"],
  "northwestern state demons": ["northwestern st demons", "northwestern state", "northwestern state demons", "nwst"],
  "northwestern wildcats": ["northwestern", "northwestern wildcats", "nw"],
  "notre dame fighting irish": ["fighting irish", "notre dame", "notre dame fighting irish", "nd"],
  "oakland golden grizzlies": ["golden grizzlies", "oakland", "oakland golden grizzlies"],
  "ohio bobcats": ["ohio", "ohio bobcats"],
  "ohio state buckeyes": ["ohio st buckeyes", "ohio state", "ohio state buckeyes", "ohio st.", "ohio st", "osu"],
  "oklahoma sooners": ["oklahoma", "oklahoma sooners", "okla", "sooners"],
  "oklahoma state cowboys": ["oklahoma st cowboys", "oklahoma state", "oklahoma state cowboys", "okst"],
  "old dominion monarchs": ["odu", "old dominion", "old dominion monarchs"],
  "ole miss rebels": ["ole miss", "ole miss rebels"],
  "omaha mavericks": ["omaha", "omaha mavericks"],
  "oral roberts golden eagles": ["oral roberts", "oral roberts golden eagles", "oru"],
  "oregon ducks": ["ore", "oregon", "oregon ducks"],
  "oregon state beavers": ["oregon st beavers", "oregon state", "oregon state beavers", "orst"],
  "pacific tigers": ["pacific", "pacific tigers", "pac"],
  "penn quakers": ["penn", "penn quakers"],
  "penn state nittany lions": ["nittany lions", "penn st. nittany lions", "penn state", "penn state nittany lions", "penn st.", "psu"],
  "pepperdine waves": ["pepp", "pepperdine", "pepperdine waves"],
  "pitt panthers": ["pitt", "pitt panthers", "pittsburgh"],
  "portland pilots": ["portland", "portland pilots", "port"],
  "portland state vikings": ["portland st vikings", "portland state", "portland state vikings", "prst"],
  "prairie view a&m panthers": ["prairie view a&m", "prairie view a&m panthers", "pvam"],
  "presbyterian blue hose": ["blue hose", "presbyterian", "presbyterian blue hose", "pres"],
  "princeton tigers": ["prince", "princeton", "princeton tigers"],
  "providence friars": ["friars", "providence", "providence friars", "prov"],
  "purdue boilermakers": ["boilermakers", "purdue", "purdue boilermakers", "pur"],
  "purdue fort wayne mastodons": ["purdue fort wayne", "purdue fort wayne mastodons"],
  "queens university of charlotte royals": ["queens", "queens university of charlotte", "queens university of charlotte royals"],
  "quinnipiac bobcats": ["quinnipiac", "quinnipiac bobcats", "quin"],
  "radford highlanders": ["radford", "radford highlanders", "rad"],
  "rhode island rams": ["rhode island", "rhode island rams", "uri"],
  "rice owls": ["rice", "rice owls"],
  "richmond spiders": ["richmond", "richmond spiders", "rich"],
  "rider broncs": ["rider", "rider broncs"],
  "robert morris colonials": ["robert morris", "robert morris colonials", "rmu"],
  "rutgers scarlet knights": ["rutgers", "rutgers scarlet knights", "rutg", "scarlet knights"],
  "sacramento state hornets": ["sacramento st hornets", "sacramento state", "sacramento state hornets", "sac"],
  "sacred heart pioneers": ["sacred heart", "sacred heart pioneers", "sh"],
  "saint francis (pa) red flash": ["red flash", "saint francis (pa)", "saint francis (pa) red flash", "sfpa"],
  "saint joseph's hawks": ["saint joseph's", "saint joseph's hawks", "sju"],
  "saint louis bilikens": ["bilikens", "saint louis", "saint louis bilikens", "slu"],
  "saint mary's gaels": ["saint mary's", "saint mary's gaels", "smc"],
  "saint peter's peacocks": ["saint peter's", "saint peter's peacocks", "sp"],
  "sam houston bearkats": ["sam houston", "sam houston bearkats", "shsu"],
  "samford bulldogs": ["samford", "samford bulldogs", "sam"],
  "san diego state aztecs": ["aztecs", "san diego st aztecs", "san diego state", "san diego st.", "san diego state aztecs", "sdsu"],
  "san diego toreros": ["san diego", "san diego toreros", "usd"],
  "san francisco dons": ["san francisco", "san francisco dons", "usf"],
  "san josé state spartans": ["san jose st spartans", "san jose state", "san josé state", "san josé state spartans", "sjsu"],
  "santa clara broncos": ["santa clara", "santa clara broncos", "sc"],
  "seattle u redhawks": ["seattle u", "seattle u redhawks"],
  "seton hall pirates": ["seton hall", "seton hall pirates", "shu"],
  "siena saints": ["siena", "siena saints", "sien"],
  "siu edwardsville cougars": ["siu edwardsville", "siu edwardsville cougars", "siue"],
  "smu mustangs": ["smu", "Southern Methodist", "smu mustangs"],
  "south alabama jaguars": ["south alabama", "south alabama jaguars", "usa"],
  "south carolina gamecocks": ["gamecocks", "s carolina", "sc", "socar", "south carolina", "south carolina gamecocks"],
  "south carolina state bulldogs": ["s carolina st bulldogs", "s carolina state", "scst", "south carolina state", "south carolina state bulldogs"],
  "south dakota coyotes": ["south dakota", "south dakota coyotes", "usd"],
  "south dakota state jackrabbits": ["jackrabbits", "sdsu", "south dakota st jackrabbits", "south dakota state", "south dakota state jackrabbits"],
  "south florida bulls": ["south florida", "south florida bulls", "usf"],
  "southeast missouri state redhawks": ["se missouri st", "se missouri st redhawks", "southeast missouri state", "southeast missouri state redhawks"],
  "southeastern louisiana lions": ["selu", "southeastern louisiana", "southeastern louisiana lions"],
  "southern colts": ["southern", "southern colts"],
  "southern illinois salukis": ["siu", "southern illinois", "southern illinois salukis"],
  "southern indiana screaming eagles": ["southern indiana", "southern indiana screaming eagles"],
  "southern miss golden eagles": ["southern miss", "southern miss golden eagles", "southern mississippi", "usm"],
  "southern utah thunderbirds": ["southern utah", "southern utah thunderbirds", "suu"],
  "st. bonaventure bonnies": ["bonnies", "st. bonaventure", "st. bonaventure bonnies", "sbu"],
  "st. francis (ny) terriers": ["st. francis (ny)", "st. francis (ny) terriers", "sfny"],
  "st. john's red storm": ["red storm", "st. johns", "st. john's", "st. john's red storm", "stj"],
  "st. thomas - minnesota tomies": ["st. thomas", "st. thomas - minnesota", "st. thomas - minnesota tomies"],
  "stanford cardinal": ["cardinal", "stanford", "stanford cardinal", "stan"],
  "stephen f. austin lumberjacks": ["lumberjacks", "sfa", "stephen f. austin", "stephen f. austin lumberjacks"],
  "stetson hatters": ["stetson", "stetson hatters"],
  "stony brook seawolves": ["stony brook", "stony brook seawolves", "stbk"],
  "syracuse orange": ["cuse", "orange", "syracuse", "syracuse orange", "syr"],
  "tarleton texans": ["tarleton", "tarleton texans", "tarl"],
  "tcu horned frogs": ["horned frogs", "tcu", "tcu horned frogs"],
  "temple owls": ["temple", "temple owls", "temp"],
  "tennessee state tigers": ["tenn st", "tenn st tigers", "tennessee state", "tennessee state tigers"],
  "tennessee tech golden eagles": ["tennessee tech", "tennessee tech golden eagles", "tntc"],
  "tennessee volunteers": ["tenn", "tennessee", "tennessee volunteers", "vols"],
  "texas a&m aggies": ["a&m", "aggies", "tamu", "texas a&m", "texas a&m aggies"],
  "texas a&m-commerce lions": ["a&m-commerce", "texas a&m-commerce", "texas a&m-commerce lions"],
  "texas longhorns": ["longhorns", "texas", "texas longhorns", "tex"],
  "texas southern tigers": ["texas southern", "texas southern tigers", "txso"],
  "texas state bobcats": ["texas st bobcats", "texas state", "texas state bobcats", "txst"],
  "texas tech red raiders": ["red raiders", "texas tech", "texas tech red raiders", "tt", "ttu"],
  "toledo rockets": ["toledo", "toledo rockets"],
  "towson tigers": ["towson", "towson tigers", "tows"],
  "troy trojans": ["troy", "troy trojans"],
  "tulane green wave": ["green wave", "tulane", "tulane green wave", "tul"],
  "tulsa golden hurricane": ["golden hurricane", "tulsa", "tulsa golden hurricane", "tls"],
  "uab blazers": ["uab", "uab blazers"],
  "uc davis aggies": ["uc davis", "uc davis aggies"],
  "uc irvine anteaters": ["anteaters", "uc irvine", "uc irvine anteaters", "uci"],
  "uc riverside highlanders": ["uc riverside", "uc riverside highlanders", "ucr"],
  "uc san diego tritons": ["uc san diego", "uc san diego tritons", "ucsd"],
  "uc santa barbara gauchos": ["gauchos", "uc santa barbara", "uc santa barbara gauchos", "ucsb"],
  "ucf knights": ["central florida", "central florida knights", "ucf", "ucf knights"],
  "ucla bruins": ["ucla", "ucla bruins"],
  "uconn huskies": ["connecticut", "connecticut huskies", "uconn", "uconn huskies"],
  "ul monroe warhawks": ["ul monroe", "Louisiana Monroe", "ul monroe warhawks", "ulm"],
  "umass minutemen": ["massachusetts", "massachusetts minutemen", "umass", "umass minutemen"],
  "umass lowell river hawks": ["river hawks", "umass lowell", "umass lowell river hawks", "uml"],
  "umbc retrievers": ["umbc", "umbc retrievers"],
  "umkc kangaroos": ["umkc", "umkc kangaroos"],
  "unc asheville bulldogs": ["unc asheville", "unc asheville bulldogs", "unca"],
  "unc greensboro spartans": ["unc greensboro", "unc greensboro spartans", "uncg"],
  "unc wilmington seahawks": ["unc wilmington", "unc wilmington seahawks", "uncw"],
  "unlv rebels": ["unlv", "unlv rebels"],
  "usc trojans": ["southern cal", "southern california", "southern california trojans", "trojans", "usc", "usc trojans"],
  "ut arlington mavericks": ["ut arlington", "ut arlington mavericks", "uta"],
  "ut martin skyhawks": ["ut martin", "ut martin skyhawks", "utm"],
  "ut rio grande valley vaqueros": ["ut rio grande valley", "ut rio grande valley vaqueros", "utrgv"],
  "utah state aggies": ["utah st aggies", "utah state", "utah state aggies", "usu"],
  "utah tech trail blazers": ["utah tech", "utah tech trail blazers"],
  "utah utes": ["utah", "utah utes", "utes"],
  "utah valley wolverines": ["utah valley", "utah valley wolverines", "uvu"],
  "utep miners": ["utep", "utep miners"],
  "utsa roadrunners": ["roadrunners", "utsa", "utsa roadrunners"],
  "vcu rams": ["vcu", "vcu rams"],
  "vmi keydets": ["vmi", "vmi keydets"],
  "valparaiso beacons": ["valparaiso", "valparaiso beacons", "valpo"],
  "vanderbilt commodores": ["commodores", "vanderbilt", "vanderbilt commodores", "vandy"],
  "vermont catamounts": ["vermont", "vermont catamounts", "uvm"],
  "villanova wildcats": ["nova", "villanova", "villanova wildcats"],
  "virginia cavaliers": ["cavaliers", "uva", "virginia", "virginia cavaliers"],
  "virginia tech hokies": ["hokies", "virginia tech", "va tech", "virginia tech hokies", "vt"],
  "wagner seahawks": ["wagner", "wagner seahawks", "wag"],
  "wake forest demon deacons": ["demon deacons", "wake", "wake forest", "wake forest demon deacons"],
  "washington huskies": ["huskies", "uw", "washington", "washington huskies"],
  "washington state cougars": ["washington st cougars", "washington state", "washington state cougars", "wazzu", "wsu"],
  "weber state wildcats": ["weber st wildcats", "weber state", "weber state wildcats", "web"],
  "west virginia mountaineers": ["west virginia", "west virginia mountaineers", "wvu"],
  "western carolina catamounts": ["western carolina", "western carolina catamounts", "wcu"],
  "western illinois leathernecks": ["western illinois", "western illinois leathernecks", "wiu"],
  "western kentucky hilltoppers": ["hilltoppers", "western kentucky", "western kentucky hilltoppers", "wku"],
  "western michigan broncos": ["western michigan", "western michigan broncos", "wmu"],
  "wichita state shockers": ["shockers", "wichita st shockers", "wichita state", "wichita state shockers", "wich"],
  "william & mary tribe": ["tribe", "w&m", "william & mary", "william & mary tribe"],
  "winthrop eagles": ["winthrop", "winthrop eagles", "win"],
  "wisconsin badgers": ["badgers", "wisconsin", "wisconsin badgers", "wisc"],
  "wofford terriers": ["wofford", "wofford terriers", "woff"],
  "wright state raiders": ["wright st raiders", "wright state", "wright state raiders", "wrst"],
  "wyoming cowboys": ["wyoming", "wyoming cowboys", "wyo"],
  "xavier musketeers": ["musketeers", "xavier", "xavier musketeers", "xav"],
  "yale bulldogs": ["yale", "yale bulldogs"],
  "youngstown state penguins": ["youngstown st penguins", "youngstown state", "youngstown state penguins", "ysu"]
}